apiVersion: apps/v1
kind: Deployment
metadata:
  name: grader-web
  namespace: jobe-web
spec:
  replicas: 1 # Scale to 2 or 3 for high availability
  selector:
    matchLabels:
      app: grader-web
  template:
    metadata:
      labels:
        app: grader-web
    spec:
      containers:
      - name: web
        image: julianowick/jobe-web:latest
        ports:
        - containerPort: 8000
        env:
        # If you need to change Jobe URL dynamically
        - name: JOBE_URL
          value: "http://jobe-service.jobe-web.svc.cluster.local:80/jobe/index.php/restapi/runs"
        - name: GIT_REPO_URL
          value: "https://github.com/inf-ufrgs/inf01040-assignments.git"
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: token
        # SAML Configuration
        - name: SAML_ENABLED
          value: "true"
        - name: SAML_SP_BASE_URL
          value: "https://jobe-web.k8s.inf.ufrgs.br"
        - name: SESSION_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: saml-creds
              key: session-secret
        volumeMounts:
        - name: saml-certs
          mountPath: /app/saml/certs
          readOnly: true
        resources:
          # Limits to ensure it doesn't drain cluster resources
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: saml-certs
        secret:
          secretName: saml-creds
          items:
          - key: sp.crt
            path: sp.crt
          - key: sp.key
            path: sp.key
---
apiVersion: v1
kind: Service
metadata:
  name: grader-service
  namespace: jobe-web
spec:
  selector:
    app: grader-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP